#!/bin/sh
#Big_Dumper_Install

#installation des pré-requis
apt-get install git binutils make csh g++ sed gawk autoconf automake autotools-dev libglib2.0-dev libnfc-dev liblzma-dev libnfc-bin libusb-dev libtool

#installation de miLazyCracker
cd /root/miLazyCracker
./miLazyCrackerFreshInstall.sh
cd ../

#installation de MFOC
cd /root/mfoc
autoreconf -vis
autoreconf -vis
./configure
./configure
make && sudo make install
cd ../

#installation de hexedit
apt-get install hexedit

#création de la commande dump
chmod +x /root/BigDumper/prog/Big_Dumper
cd /usr/bin
ln -s /root/BigDumper/prog/Big_Dumper dump
cd ../