#!/bin/sh
#miLazyCracker

##COULEURS##
r="\033[1;31m" #rouge
n="\033[0m" #normal
##

bon=n

cd miLazyCracker
cd crypto1_bs
clear
		
until [ $bon = y ]||[ $bon = yes ]||[ $bon = oui ]||[ $bon = o ]||[ $bon = Y ]||[ $bon = O ] ; do
		clear
		
		echo $r"Clé connue:"$n
		read cle1

		echo $r"Numéro du secteur connu X 4:"$n
		read secteur

		echo $r"Clé A ou B?"$n
		read cle2

		echo $r"Clé cherchée du même secteur (A ou B):"$n
		read cle3
		
		echo $r"Tout est correcte? (y/n)"$n
		read bon
	done
clear

./libnfc_crypto1_crack $cle1 $secteur $cle2 $secteur cle3
#./libnfc_crypto1_crack <known key> <NumeroSecteurConnu[x]4(nbr de bloc)> <A|B> <BLOCK RECHERCHE (même que précédant)> <A|B>